import { mkdirSync } from 'node:fs'
import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import Database from 'better-sqlite3'
import { drizzle, type BetterSQLite3Database } from 'drizzle-orm/better-sqlite3'
import { migrate } from 'drizzle-orm/better-sqlite3/migrator'
import * as schema from './schema'

/**
 * The Drizzle migrations generated by drizzle-kit for this schema. Resolved
 * from this module's own URL rather than `process.cwd()`, because the tests
 * and `tsx` run from different working directories.
 */
export const MIGRATIONS_FOLDER = fileURLToPath(new URL('./migrations', import.meta.url))

export type AppDatabase = BetterSQLite3Database<typeof schema>

export interface DatabaseHandle {
  db: AppDatabase
  sqlite: Database.Database
  close(): void
}

/**
 * Opens a SQLite database at `filePath`, creating the parent directory if
 * needed. Foreign keys are off by default in SQLite and must be turned on
 * per connection, or a purchase could reference a fund that does not exist.
 */
export function openDatabase(filePath: string): DatabaseHandle {
  mkdirSync(dirname(filePath), { recursive: true })

  const sqlite = new Database(filePath)
  sqlite.pragma('journal_mode = WAL')
  sqlite.pragma('foreign_keys = ON')

  const db = drizzle(sqlite, { schema })

  return {
    db,
    sqlite,
    close() {
      sqlite.close()
    },
  }
}

/** Applies every migration under `MIGRATIONS_FOLDER` to the given handle. */
export function applyMigrations(handle: DatabaseHandle): void {
  migrate(handle.db, { migrationsFolder: MIGRATIONS_FOLDER })
}
